name: Clashkissez CI
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Build the code
        run: |
          cd ${{ github.workspace }};
          docker-compose build;
      - run: echo "This job's status is ${{ job.status }}."
