name: Clashkissez CI
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build the code
        run: docker-compose build
