name: Clashkissez CI
on: 
  - push 
  - workflow_dispatch
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: echo "BUILD_TYPE=${{ secrets.BUILD_TYPE }}" > .env
      - run: echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> .env
      - run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      - name: Build the code
        run: docker-compose build
